FROM fedora:latest
RUN dnf -y update
EXPOSE 5000
VOLUME /app
WORKDIR /app
RUN pip3 install flask flask_script
COPY json-server.py /app
COPY read_jason /app
COPY write_json /app
CMD ["python3","json-server.py","read_jason","write_json"]